// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_rls_dnn_top.h for the primary calling header

#ifndef VERILATED_VTB_RLS_DNN_TOP___024ROOT_H_
#define VERILATED_VTB_RLS_DNN_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_rls_dnn_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_rls_dnn_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_rls_dnn_top__DOT__clk;
        CData/*0:0*/ tb_rls_dnn_top__DOT__rst_n;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_aad__rst_n;
        CData/*0:0*/ tb_rls_dnn_top__DOT__sample_enable;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axis_tvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axis_tready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__m_axis_tvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__m_axis_tready;
        CData/*7:0*/ tb_rls_dnn_top__DOT__s_axi_awaddr;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axi_awvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axi_wvalid;
        CData/*1:0*/ tb_rls_dnn_top__DOT__s_axi_bresp;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axi_bvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axi_bready;
        CData/*7:0*/ tb_rls_dnn_top__DOT__s_axi_araddr;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axi_arvalid;
        CData/*1:0*/ tb_rls_dnn_top__DOT__s_axi_rresp;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axi_rvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__s_axi_rready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__cbpf_y_valid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__cbpf_clip_s1;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__cbpf_clip_s2;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__aad_signal_active;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__aad_clk_gate_en;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__rcim_ref_channel_fault;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__rls_valid_out;
        CData/*1:0*/ tb_rls_dnn_top__DOT__dut__DOT__affhc_fsm_state_dbg;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__mlp_valid_out;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__plwd_pipeline_srst;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__plwd_irq_fault;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__poly_rls_en;
        CData/*2:0*/ tb_rls_dnn_top__DOT__dut__DOT__poly_decim_cnt_dbg;
        CData/*2:0*/ tb_rls_dnn_top__DOT__dut__DOT__decim_ratio;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__sample_consumed_cbpf;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__decim_q;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__rls_en;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_cbpf__s_axi_wvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_cbpf__s_axi_awvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_aad__s_axi_wvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_aad__s_axi_awvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_rcim__s_axi_wvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_rcim__s_axi_awvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_affhc__s_axi_wvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_affhc__s_axi_awvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_plwd__s_axi_wvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_plwd__s_axi_awvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_plwd__s_axi_arvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__latprof_rvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_latprof__s_axi_arvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__affhc_awready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__affhc_wready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__aad_awready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__aad_wready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__cbpf_awready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__cbpf_wready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__plwd_awready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__plwd_wready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__rcim_awready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__rcim_wready;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__plwd_rvalid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vlvbound_h960a4189__1;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT____VdfgRegularize_h739c3624_2_0;
        CData/*2:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_poly__DOT__decim_cnt;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__bypass_reg;
    };
    struct {
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__s1_valid_stg1;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__s1_valid_stg2;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__s2_valid_stg1;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__s2_valid_stg2;
        CData/*3:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__ratio_shift_reg;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__activity_cmp;
        CData/*2:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__assert_cnt;
        CData/*6:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__deassert_cnt;
        CData/*3:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__ratio_shift;
        CData/*7:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__fault_cnt;
        CData/*7:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__recover_cnt;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__s1_valid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__nr_p1_valid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__nr_p2_valid;
        CData/*2:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE1_NR1__DOT__NR_STAGE1__DOT__lut_idx;
        CData/*1:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__state;
        CData/*1:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__next_state;
        CData/*2:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__cnt_up;
        CData/*3:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__cnt_down;
        CData/*5:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__lockout_cnt;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__lockout_active;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__s0_valid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__s1_valid;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__pipeline_stall_fault;
        CData/*4:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__stuck_cnt;
        CData/*0:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__output_stuck_fault;
        CData/*1:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__fault_type_reg;
        CData/*7:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__fault_count_reg;
        CData/*1:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__rcv_state;
        CData/*2:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__drain_cnt;
        CData/*0:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__pipeline_stall_fault;
        CData/*0:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__output_stuck_fault;
        CData/*1:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__rcv_state;
        CData/*7:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__fault_count_reg;
        CData/*0:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__s1_valid_stg2;
        CData/*0:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__rcim_ref_channel_fault;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v0;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v6;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v7;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v8;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v9;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v10;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v11;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__x_dly__v0;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__x_dly__v8;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v0;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v1;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v2;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v3;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v4;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v5;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v6;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v7;
        CData/*0:0*/ __VdlySet__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v8;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_rls_dnn_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_rls_dnn_top__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_rls_dnn_top__DOT__dut__DOT____Vcellinp__u_aad__rst_n__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb_rls_dnn_top__DOT__m_axis_tdata;
        SData/*15:0*/ tb_rls_dnn_top__DOT__d_sample;
        SData/*15:0*/ tb_rls_dnn_top__DOT__x_sample;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__x_cbpf;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__rcim_x_out_muxed;
    };
    struct {
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__rls_error;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__rls_y_hat;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__affhc_lambda_out;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__mlp_noise_est;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__fwes_e_weighted;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__rls_leak_factor;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__fwes_alpha_reg;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vlvbound_h2eb1b900__1;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT____Vlvbound_h6be89c00__1;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__y_s1_trunc;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__y_s2_trunc;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__corr_threshold;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__recip_approx;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_fwes__DOT__e_w_prev;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__p_scalar;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__e_reg;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__d_pipe;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__nr_denom_p1;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__nr_x1;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__nr_x2;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__e_reg_p1;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__d_pipe_p1;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE1_NR1__DOT__NR_STAGE1__DOT__d_norm;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE1_NR1__DOT__NR_STAGE1__DOT__x0;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE1_NR1__DOT__NR_STAGE1__DOT__residual1;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__residual2;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__unnamedblk2__DOT__update_err;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__lambda_slow;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__lambda_mid;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__lambda_fast;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__threshold_up_reg;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__threshold_down_reg;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__e_prev;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__timeout_cnt;
        SData/*15:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__last_sample;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v6;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v7;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v8;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v9;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v10;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__d_dly__v11;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v0;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v1;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v2;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v3;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v4;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v5;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v6;
        SData/*15:0*/ __VdlyVal__tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w__v7;
        IData/*31:0*/ tb_rls_dnn_top__DOT__s_axis_tdata;
        IData/*31:0*/ tb_rls_dnn_top__DOT__s_axi_wdata;
        IData/*31:0*/ tb_rls_dnn_top__DOT__s_axi_rdata;
        IData/*31:0*/ tb_rls_dnn_top__DOT__clk_cnt;
        IData/*31:0*/ tb_rls_dnn_top__DOT__sample_idx;
        IData/*31:0*/ tb_rls_dnn_top__DOT__out_cnt;
        IData/*31:0*/ tb_rls_dnn_top__DOT__pass_cnt;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__i;
        IData/*16:0*/ tb_rls_dnn_top__DOT__dut__DOT__sub_full;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__latprof_rdata;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__plwd_rdata;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__w1_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__w2_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__w0_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__y_s1;
    };
    struct {
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_a1_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_a2_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_b0_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_b1_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_b2_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__w1_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__w2_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__w0_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__y_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_a1_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_a2_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_b0_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_b1_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__mul_b2_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__x_sq;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__mul_tmp;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__mul_dx;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__mul_xx;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__nr_term;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__nr_prod;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__mul_nr1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__mul_nr2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__norm_corr_prod;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__mul_norm;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_fwes__DOT__unnamedblk1__DOT__alpha_term;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__i;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__mul_tmp;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE0__DOT__DOT_PRODUCT__DOT__j;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE1_NR1__DOT__NR_STAGE1__DOT__denom;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE1_NR1__DOT__NR_STAGE1__DOT__Dx0;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__Dx1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__p_over_denom;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__ke;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__unnamedblk2__DOT__w_leaked;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE2_NR2__DOT__unnamedblk1__DOT__P_UPDATE__DOT__p_new;
        IData/*16:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_affhc__DOT__delta_e;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_ptdl__DOT__i;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__ii;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__mul_s0;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__mul_s1;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__mul_s2;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER1__DOT__L1_COMPUTE__DOT__n;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER1__DOT__L1_COMPUTE__DOT__k;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER2__DOT__L2_COMPUTE__DOT__n;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER2__DOT__L2_COMPUTE__DOT__k;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER3__DOT__L3_COMPUTE__DOT__k;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__global_sample_cnt;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__fault_sample_cnt;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__free_cnt;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__ts_cbpf;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__ts_rls;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__ts_ptdl;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__ts_mlp;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__ts_output;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__lat_cbpf_to_rls;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__lat_rls_to_ptdl;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__lat_ptdl_to_mlp;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__lat_mlp_to_out;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__lat_total;
        IData/*31:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__free_cnt_snap;
        IData/*31:0*/ __Vdly__tb_rls_dnn_top__DOT__clk_cnt;
        IData/*31:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_latprof__DOT__free_cnt;
        IData/*31:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_plwd__DOT__global_sample_cnt;
    };
    struct {
        IData/*31:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__y_s2;
        IData/*31:0*/ __Vdly__tb_rls_dnn_top__DOT__dut__DOT__u_cbpf__DOT__w0_s2;
        IData/*31:0*/ __VactIterCount;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__acc_A_dbg;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__acc_B_dbg;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__acc_A;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_aad__DOT__acc_B;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__corr_acc;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__ref_power_acc;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__y_acc;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__xTx_acc;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE0__DOT__DOT_PRODUCT__DOT__acc_y;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__STAGE0__DOT__DOT_PRODUCT__DOT__acc_xx;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER1__DOT__L1_COMPUTE__DOT__acc;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER2__DOT__L2_COMPUTE__DOT__acc;
        QData/*39:0*/ tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__LAYER3__DOT__L3_COMPUTE__DOT__acc;
        VlUnpacked<SData/*15:0*/, 6> tb_rls_dnn_top__DOT__dut__DOT__d_dly;
        VlUnpacked<SData/*15:0*/, 3> tb_rls_dnn_top__DOT__dut__DOT__rls_err_pipe;
        VlUnpacked<CData/*0:0*/, 3> tb_rls_dnn_top__DOT__dut__DOT__rls_vld_pipe;
        VlUnpacked<SData/*15:0*/, 16> tb_rls_dnn_top__DOT__dut__DOT__u_rcim__DOT__lutram;
        VlUnpacked<SData/*15:0*/, 8> tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__w;
        VlUnpacked<SData/*15:0*/, 8> tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__x_dly;
        VlUnpacked<SData/*15:0*/, 8> tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__nr_lut;
        VlUnpacked<SData/*15:0*/, 8> tb_rls_dnn_top__DOT__dut__DOT__u_rls__DOT__x_dly_p1;
        VlUnpacked<SData/*15:0*/, 8> tb_rls_dnn_top__DOT__dut__DOT__u_ptdl__DOT__sr;
        VlUnpacked<SData/*15:0*/, 512> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__w1_rom;
        VlUnpacked<SData/*15:0*/, 64> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__b1_rom;
        VlUnpacked<SData/*15:0*/, 2048> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__w2_rom;
        VlUnpacked<SData/*15:0*/, 32> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__b2_rom;
        VlUnpacked<SData/*15:0*/, 32> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__w3_rom;
        VlUnpacked<SData/*15:0*/, 1> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__b3_rom;
        VlUnpacked<SData/*15:0*/, 8> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__feat;
        VlUnpacked<SData/*15:0*/, 64> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__h1;
        VlUnpacked<SData/*15:0*/, 32> tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__h2;
        VlUnpacked<CData/*0:0*/, 14> __Vm_traceActivity;
    };
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 32>, false, SData/*15:0*/, 1> __VdlyCommitQueue__tb_rls_dnn_top__DOT__dut__DOT__u_mlp__DOT__h2__v0;
    double tb_rls_dnn_top__DOT__sin_val;
    double tb_rls_dnn_top__DOT__noise_val;
    double tb_rls_dnn_top__DOT__sin_lut__Vstatic__angle;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h65953776__0;
    VlTriggerScheduler __VtrigSched_h65953737__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<5> __VactTriggered;
    VlTriggerVec<5> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_rls_dnn_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_rls_dnn_top___024root(Vtb_rls_dnn_top__Syms* symsp, const char* v__name);
    ~Vtb_rls_dnn_top___024root();
    VL_UNCOPYABLE(Vtb_rls_dnn_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
