#!/usr/bin/env python3
"""
Export trained MHDA MLP weights to Q1.15 Verilog localparam include file.
Output: rtl/mlp_weights.vh — 6 localparam lines matching mlp_inference.v.
"""
# SPDX-License-Identifier: Apache-2.0

import os, sys, argparse, datetime, json, re
import numpy as np
import torch

from mhda_mlp import MHDA_MLP

LAYER_NAMES = {
    "fc1.weight": ("W1_INIT", 1024),     # 8*128
    "fc1.bias":   ("B1_INIT", 128),
    "fc2.weight": ("W2_INIT", 49152),    # 128*384
    "fc2.bias":   ("B2_INIT", 384),
    "fc3.weight": ("W3_INIT", 49152),    # 384*128
    "fc3.bias":   ("B3_INIT", 128),
    "fc4.weight": ("W4_INIT", 128),      # 128*1
    "fc4.bias":   ("B4_INIT", 1),
}

def quantize_to_q15(tensor_np):
    """Convert float32 numpy array to Q1.15 int16 array."""
    return np.round(tensor_np * 32768).clip(-32768, 32767).astype(np.int16)

def tensor_to_hex(tensor_q15):
    """Flatten row-major, convert to hex string (MSB first)."""
    flat = tensor_q15.flatten()  # row-major (C order)
    return "".join(f"{(int(v) & 0xFFFF):04X}" for v in flat)

def export(args):
    model = MHDA_MLP()
    state = torch.load(args.model, map_location="cpu")
    model.load_state_dict(state)
    model.eval()

    # Load metrics if available
    test_snr = "?"
    test_enob = "?"
    metrics_file = os.path.join(os.path.dirname(args.model), "train_metrics.json")
    if os.path.exists(metrics_file):
        with open(metrics_file) as f:
            m = json.load(f)
            test_snr = f"{m['test_snr']:.2f}"
            test_enob = f"{m['test_enob']:.2f}"

    lines = []
    lines.append("// Auto-generated by scripts/export_weights.py")
    lines.append(f"// Model: {args.model}")
    lines.append(f"// Test SNR: {test_snr} dB  Test ENOB: {test_enob} bits")
    lines.append(f"// Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    all_stats = {}
    for layer_name, (vh_name, n_entries) in LAYER_NAMES.items():
        tensor = state[layer_name].numpy()
        t_q15 = quantize_to_q15(tensor)
        hex_str = tensor_to_hex(t_q15)

        if len(hex_str) != n_entries * 4:
            print(f"ERROR: {vh_name}: expected {n_entries*4} hex chars, got {len(hex_str)}")
            sys.exit(1)

        lines.append(f"localparam [{n_entries}*16-1:0] {vh_name} = {n_entries*16}'h{hex_str};")

        stats = {
            "min": int(t_q15.min()),
            "max": int(t_q15.max()),
            "zeros": int(np.sum(t_q15 == 0)),
            "saturation_pct": float(np.sum(np.abs(t_q15) == 32767) / t_q15.size * 100),
        }
        all_stats[vh_name] = stats
        print(f"{vh_name}: min={stats['min']} max={stats['max']} "
              f"zeros={stats['zeros']} saturation={stats['saturation_pct']:.2f}%")

    lines.append("")

    out_path = args.out
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nExported {sum(v[1] for v in LAYER_NAMES.values())} weights to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export MHDA MLP weights to Verilog")
    parser.add_argument("--model", type=str, default="models/best_mlp.pt")
    parser.add_argument("--out", type=str, default="rtl/mlp_weights.vh")
    args = parser.parse_args()
    export(args)
