
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point srst srst -type PI PI
add mapped point sample_en sample_en -type PI PI
add mapped point d_in[15] d_in[15] -type PI PI
add mapped point d_in[14] d_in[14] -type PI PI
add mapped point d_in[13] d_in[13] -type PI PI
add mapped point d_in[12] d_in[12] -type PI PI
add mapped point d_in[11] d_in[11] -type PI PI
add mapped point d_in[10] d_in[10] -type PI PI
add mapped point d_in[9] d_in[9] -type PI PI
add mapped point d_in[8] d_in[8] -type PI PI
add mapped point d_in[7] d_in[7] -type PI PI
add mapped point d_in[6] d_in[6] -type PI PI
add mapped point d_in[5] d_in[5] -type PI PI
add mapped point d_in[4] d_in[4] -type PI PI
add mapped point d_in[3] d_in[3] -type PI PI
add mapped point d_in[2] d_in[2] -type PI PI
add mapped point d_in[1] d_in[1] -type PI PI
add mapped point d_in[0] d_in[0] -type PI PI
add mapped point x_in[15] x_in[15] -type PI PI
add mapped point x_in[14] x_in[14] -type PI PI
add mapped point x_in[13] x_in[13] -type PI PI
add mapped point x_in[12] x_in[12] -type PI PI
add mapped point x_in[11] x_in[11] -type PI PI
add mapped point x_in[10] x_in[10] -type PI PI
add mapped point x_in[9] x_in[9] -type PI PI
add mapped point x_in[8] x_in[8] -type PI PI
add mapped point x_in[7] x_in[7] -type PI PI
add mapped point x_in[6] x_in[6] -type PI PI
add mapped point x_in[5] x_in[5] -type PI PI
add mapped point x_in[4] x_in[4] -type PI PI
add mapped point x_in[3] x_in[3] -type PI PI
add mapped point x_in[2] x_in[2] -type PI PI
add mapped point x_in[1] x_in[1] -type PI PI
add mapped point x_in[0] x_in[0] -type PI PI
add mapped point lambda_in[15] lambda_in[15] -type PI PI
add mapped point lambda_in[14] lambda_in[14] -type PI PI
add mapped point lambda_in[13] lambda_in[13] -type PI PI
add mapped point lambda_in[12] lambda_in[12] -type PI PI
add mapped point lambda_in[11] lambda_in[11] -type PI PI
add mapped point lambda_in[10] lambda_in[10] -type PI PI
add mapped point lambda_in[9] lambda_in[9] -type PI PI
add mapped point lambda_in[8] lambda_in[8] -type PI PI
add mapped point lambda_in[7] lambda_in[7] -type PI PI
add mapped point lambda_in[6] lambda_in[6] -type PI PI
add mapped point lambda_in[5] lambda_in[5] -type PI PI
add mapped point lambda_in[4] lambda_in[4] -type PI PI
add mapped point lambda_in[3] lambda_in[3] -type PI PI
add mapped point lambda_in[2] lambda_in[2] -type PI PI
add mapped point lambda_in[1] lambda_in[1] -type PI PI
add mapped point lambda_in[0] lambda_in[0] -type PI PI
add mapped point leak_factor[15] leak_factor[15] -type PI PI
add mapped point leak_factor[14] leak_factor[14] -type PI PI
add mapped point leak_factor[13] leak_factor[13] -type PI PI
add mapped point leak_factor[12] leak_factor[12] -type PI PI
add mapped point leak_factor[11] leak_factor[11] -type PI PI
add mapped point leak_factor[10] leak_factor[10] -type PI PI
add mapped point leak_factor[9] leak_factor[9] -type PI PI
add mapped point leak_factor[8] leak_factor[8] -type PI PI
add mapped point leak_factor[7] leak_factor[7] -type PI PI
add mapped point leak_factor[6] leak_factor[6] -type PI PI
add mapped point leak_factor[5] leak_factor[5] -type PI PI
add mapped point leak_factor[4] leak_factor[4] -type PI PI
add mapped point leak_factor[3] leak_factor[3] -type PI PI
add mapped point leak_factor[2] leak_factor[2] -type PI PI
add mapped point leak_factor[1] leak_factor[1] -type PI PI
add mapped point leak_factor[0] leak_factor[0] -type PI PI
add mapped point e_weighted[15] e_weighted[15] -type PI PI
add mapped point e_weighted[14] e_weighted[14] -type PI PI
add mapped point e_weighted[13] e_weighted[13] -type PI PI
add mapped point e_weighted[12] e_weighted[12] -type PI PI
add mapped point e_weighted[11] e_weighted[11] -type PI PI
add mapped point e_weighted[10] e_weighted[10] -type PI PI
add mapped point e_weighted[9] e_weighted[9] -type PI PI
add mapped point e_weighted[8] e_weighted[8] -type PI PI
add mapped point e_weighted[7] e_weighted[7] -type PI PI
add mapped point e_weighted[6] e_weighted[6] -type PI PI
add mapped point e_weighted[5] e_weighted[5] -type PI PI
add mapped point e_weighted[4] e_weighted[4] -type PI PI
add mapped point e_weighted[3] e_weighted[3] -type PI PI
add mapped point e_weighted[2] e_weighted[2] -type PI PI
add mapped point e_weighted[1] e_weighted[1] -type PI PI
add mapped point e_weighted[0] e_weighted[0] -type PI PI

//output ports
add mapped point error_out[15] error_out[15] -type PO PO
add mapped point error_out[14] error_out[14] -type PO PO
add mapped point error_out[13] error_out[13] -type PO PO
add mapped point error_out[12] error_out[12] -type PO PO
add mapped point error_out[11] error_out[11] -type PO PO
add mapped point error_out[10] error_out[10] -type PO PO
add mapped point error_out[9] error_out[9] -type PO PO
add mapped point error_out[8] error_out[8] -type PO PO
add mapped point error_out[7] error_out[7] -type PO PO
add mapped point error_out[6] error_out[6] -type PO PO
add mapped point error_out[5] error_out[5] -type PO PO
add mapped point error_out[4] error_out[4] -type PO PO
add mapped point error_out[3] error_out[3] -type PO PO
add mapped point error_out[2] error_out[2] -type PO PO
add mapped point error_out[1] error_out[1] -type PO PO
add mapped point error_out[0] error_out[0] -type PO PO
add mapped point valid_out valid_out -type PO PO
add mapped point y_hat[15] y_hat[15] -type PO PO
add mapped point y_hat[14] y_hat[14] -type PO PO
add mapped point y_hat[13] y_hat[13] -type PO PO
add mapped point y_hat[12] y_hat[12] -type PO PO
add mapped point y_hat[11] y_hat[11] -type PO PO
add mapped point y_hat[10] y_hat[10] -type PO PO
add mapped point y_hat[9] y_hat[9] -type PO PO
add mapped point y_hat[8] y_hat[8] -type PO PO
add mapped point y_hat[7] y_hat[7] -type PO PO
add mapped point y_hat[6] y_hat[6] -type PO PO
add mapped point y_hat[5] y_hat[5] -type PO PO
add mapped point y_hat[4] y_hat[4] -type PO PO
add mapped point y_hat[3] y_hat[3] -type PO PO
add mapped point y_hat[2] y_hat[2] -type PO PO
add mapped point y_hat[1] y_hat[1] -type PO PO
add mapped point y_hat[0] y_hat[0] -type PO PO
add mapped point nr_x2_debug[15] nr_x2_debug[15] -type PO PO
add mapped point nr_x2_debug[14] nr_x2_debug[14] -type PO PO
add mapped point nr_x2_debug[13] nr_x2_debug[13] -type PO PO
add mapped point nr_x2_debug[12] nr_x2_debug[12] -type PO PO
add mapped point nr_x2_debug[11] nr_x2_debug[11] -type PO PO
add mapped point nr_x2_debug[10] nr_x2_debug[10] -type PO PO
add mapped point nr_x2_debug[9] nr_x2_debug[9] -type PO PO
add mapped point nr_x2_debug[8] nr_x2_debug[8] -type PO PO
add mapped point nr_x2_debug[7] nr_x2_debug[7] -type PO PO
add mapped point nr_x2_debug[6] nr_x2_debug[6] -type PO PO
add mapped point nr_x2_debug[5] nr_x2_debug[5] -type PO PO
add mapped point nr_x2_debug[4] nr_x2_debug[4] -type PO PO
add mapped point nr_x2_debug[3] nr_x2_debug[3] -type PO PO
add mapped point nr_x2_debug[2] nr_x2_debug[2] -type PO PO
add mapped point nr_x2_debug[1] nr_x2_debug[1] -type PO PO
add mapped point nr_x2_debug[0] nr_x2_debug[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point u_rls/d_pipe_p1[0]/q u_rls/d_pipe_p1_reg[0]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[1]/q u_rls/d_pipe_p1_reg[1]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[2]/q u_rls/d_pipe_p1_reg[2]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[3]/q u_rls/d_pipe_p1_reg[3]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[4]/q u_rls/d_pipe_p1_reg[4]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[5]/q u_rls/d_pipe_p1_reg[5]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[6]/q u_rls/d_pipe_p1_reg[6]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[7]/q u_rls/d_pipe_p1_reg[7]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[8]/q u_rls/d_pipe_p1_reg[8]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[9]/q u_rls/d_pipe_p1_reg[9]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[10]/q u_rls/d_pipe_p1_reg[10]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[11]/q u_rls/d_pipe_p1_reg[11]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[12]/q u_rls/d_pipe_p1_reg[12]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[13]/q u_rls/d_pipe_p1_reg[13]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[14]/q u_rls/d_pipe_p1_reg[14]/Q -type DFF DFF
add mapped point u_rls/d_pipe_p1[15]/q u_rls/d_pipe_p1_reg[15]/Q -type DFF DFF
add mapped point u_rls/d_pipe[0]/q u_rls/d_pipe_reg[0]/Q -type DFF DFF
add mapped point u_rls/d_pipe[1]/q u_rls/d_pipe_reg[1]/Q -type DFF DFF
add mapped point u_rls/d_pipe[2]/q u_rls/d_pipe_reg[2]/Q -type DFF DFF
add mapped point u_rls/d_pipe[3]/q u_rls/d_pipe_reg[3]/Q -type DFF DFF
add mapped point u_rls/d_pipe[4]/q u_rls/d_pipe_reg[4]/Q -type DFF DFF
add mapped point u_rls/d_pipe[5]/q u_rls/d_pipe_reg[5]/Q -type DFF DFF
add mapped point u_rls/d_pipe[6]/q u_rls/d_pipe_reg[6]/Q -type DFF DFF
add mapped point u_rls/d_pipe[7]/q u_rls/d_pipe_reg[7]/Q -type DFF DFF
add mapped point u_rls/d_pipe[8]/q u_rls/d_pipe_reg[8]/Q -type DFF DFF
add mapped point u_rls/d_pipe[9]/q u_rls/d_pipe_reg[9]/Q -type DFF DFF
add mapped point u_rls/d_pipe[10]/q u_rls/d_pipe_reg[10]/Q -type DFF DFF
add mapped point u_rls/d_pipe[11]/q u_rls/d_pipe_reg[11]/Q -type DFF DFF
add mapped point u_rls/d_pipe[12]/q u_rls/d_pipe_reg[12]/Q -type DFF DFF
add mapped point u_rls/d_pipe[13]/q u_rls/d_pipe_reg[13]/Q -type DFF DFF
add mapped point u_rls/d_pipe[14]/q u_rls/d_pipe_reg[14]/Q -type DFF DFF
add mapped point u_rls/d_pipe[15]/q u_rls/d_pipe_reg[15]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[0]/q u_rls/e_reg_p1_reg[0]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[1]/q u_rls/e_reg_p1_reg[1]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[2]/q u_rls/e_reg_p1_reg[2]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[3]/q u_rls/e_reg_p1_reg[3]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[4]/q u_rls/e_reg_p1_reg[4]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[5]/q u_rls/e_reg_p1_reg[5]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[6]/q u_rls/e_reg_p1_reg[6]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[7]/q u_rls/e_reg_p1_reg[7]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[8]/q u_rls/e_reg_p1_reg[8]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[9]/q u_rls/e_reg_p1_reg[9]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[10]/q u_rls/e_reg_p1_reg[10]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[11]/q u_rls/e_reg_p1_reg[11]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[12]/q u_rls/e_reg_p1_reg[12]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[13]/q u_rls/e_reg_p1_reg[13]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[14]/q u_rls/e_reg_p1_reg[14]/Q -type DFF DFF
add mapped point u_rls/e_reg_p1[15]/q u_rls/e_reg_p1_reg[15]/Q -type DFF DFF
add mapped point u_rls/e_reg[0]/q u_rls/e_reg_reg[0]/Q -type DFF DFF
add mapped point u_rls/e_reg[1]/q u_rls/e_reg_reg[1]/Q -type DFF DFF
add mapped point u_rls/e_reg[2]/q u_rls/e_reg_reg[2]/Q -type DFF DFF
add mapped point u_rls/e_reg[3]/q u_rls/e_reg_reg[3]/Q -type DFF DFF
add mapped point u_rls/e_reg[4]/q u_rls/e_reg_reg[4]/Q -type DFF DFF
add mapped point u_rls/e_reg[5]/q u_rls/e_reg_reg[5]/Q -type DFF DFF
add mapped point u_rls/e_reg[6]/q u_rls/e_reg_reg[6]/Q -type DFF DFF
add mapped point u_rls/e_reg[7]/q u_rls/e_reg_reg[7]/Q -type DFF DFF
add mapped point u_rls/e_reg[8]/q u_rls/e_reg_reg[8]/Q -type DFF DFF
add mapped point u_rls/e_reg[9]/q u_rls/e_reg_reg[9]/Q -type DFF DFF
add mapped point u_rls/e_reg[10]/q u_rls/e_reg_reg[10]/Q -type DFF DFF
add mapped point u_rls/e_reg[11]/q u_rls/e_reg_reg[11]/Q -type DFF DFF
add mapped point u_rls/e_reg[12]/q u_rls/e_reg_reg[12]/Q -type DFF DFF
add mapped point u_rls/e_reg[13]/q u_rls/e_reg_reg[13]/Q -type DFF DFF
add mapped point u_rls/e_reg[14]/q u_rls/e_reg_reg[14]/Q -type DFF DFF
add mapped point u_rls/e_reg[15]/q u_rls/e_reg_reg[15]/Q -type DFF DFF
add mapped point u_rls/error_out[0]/q u_rls/error_out_reg[0]/Q -type DFF DFF
add mapped point u_rls/error_out[1]/q u_rls/error_out_reg[1]/Q -type DFF DFF
add mapped point u_rls/error_out[2]/q u_rls/error_out_reg[2]/Q -type DFF DFF
add mapped point u_rls/error_out[3]/q u_rls/error_out_reg[3]/Q -type DFF DFF
add mapped point u_rls/error_out[4]/q u_rls/error_out_reg[4]/Q -type DFF DFF
add mapped point u_rls/error_out[5]/q u_rls/error_out_reg[5]/Q -type DFF DFF
add mapped point u_rls/error_out[6]/q u_rls/error_out_reg[6]/Q -type DFF DFF
add mapped point u_rls/error_out[7]/q u_rls/error_out_reg[7]/Q -type DFF DFF
add mapped point u_rls/error_out[8]/q u_rls/error_out_reg[8]/Q -type DFF DFF
add mapped point u_rls/error_out[9]/q u_rls/error_out_reg[9]/Q -type DFF DFF
add mapped point u_rls/error_out[10]/q u_rls/error_out_reg[10]/Q -type DFF DFF
add mapped point u_rls/error_out[11]/q u_rls/error_out_reg[11]/Q -type DFF DFF
add mapped point u_rls/error_out[12]/q u_rls/error_out_reg[12]/Q -type DFF DFF
add mapped point u_rls/error_out[13]/q u_rls/error_out_reg[13]/Q -type DFF DFF
add mapped point u_rls/error_out[14]/q u_rls/error_out_reg[14]/Q -type DFF DFF
add mapped point u_rls/error_out[15]/q u_rls/error_out_reg[15]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[0]/q u_rls/nr_denom_p1_reg[0]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[1]/q u_rls/nr_denom_p1_reg[1]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[2]/q u_rls/nr_denom_p1_reg[2]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[3]/q u_rls/nr_denom_p1_reg[3]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[4]/q u_rls/nr_denom_p1_reg[4]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[5]/q u_rls/nr_denom_p1_reg[5]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[6]/q u_rls/nr_denom_p1_reg[6]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[7]/q u_rls/nr_denom_p1_reg[7]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[8]/q u_rls/nr_denom_p1_reg[8]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[9]/q u_rls/nr_denom_p1_reg[9]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[10]/q u_rls/nr_denom_p1_reg[10]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[11]/q u_rls/nr_denom_p1_reg[11]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[12]/q u_rls/nr_denom_p1_reg[12]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[13]/q u_rls/nr_denom_p1_reg[13]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[14]/q u_rls/nr_denom_p1_reg[14]/Q -type DFF DFF
add mapped point u_rls/nr_denom_p1[15]/q u_rls/nr_denom_p1_reg[15]/Q -type DFF DFF
add mapped point u_rls/nr_p1_valid/q u_rls/nr_p1_valid_reg/Q -type DFF DFF
add mapped point u_rls/nr_x1[0]/q u_rls/nr_x1_reg[0]/Q -type DFF DFF
add mapped point u_rls/nr_x1[1]/q u_rls/nr_x1_reg[1]/Q -type DFF DFF
add mapped point u_rls/nr_x1[2]/q u_rls/nr_x1_reg[2]/Q -type DFF DFF
add mapped point u_rls/nr_x1[3]/q u_rls/nr_x1_reg[3]/Q -type DFF DFF
add mapped point u_rls/nr_x1[4]/q u_rls/nr_x1_reg[4]/QN -type DFF DFF
add mapped point u_rls/nr_x1[5]/q u_rls/nr_x1_reg[5]/Q -type DFF DFF
add mapped point u_rls/nr_x1[6]/q u_rls/nr_x1_reg[6]/QN -type DFF DFF
add mapped point u_rls/nr_x1[7]/q u_rls/nr_x1_reg[7]/QN -type DFF DFF
add mapped point u_rls/nr_x1[8]/q u_rls/nr_x1_reg[8]/Q -type DFF DFF
add mapped point u_rls/nr_x1[9]/q u_rls/nr_x1_reg[9]/QN -type DFF DFF
add mapped point u_rls/nr_x1[10]/q u_rls/nr_x1_reg[10]/QN -type DFF DFF
add mapped point u_rls/nr_x1[11]/q u_rls/nr_x1_reg[11]/QN -type DFF DFF
add mapped point u_rls/nr_x1[12]/q u_rls/nr_x1_reg[12]/QN -type DFF DFF
add mapped point u_rls/nr_x1[13]/q u_rls/nr_x1_reg[13]/QN -type DFF DFF
add mapped point u_rls/nr_x1[14]/q u_rls/nr_x1_reg[14]/QN -type DFF DFF
add mapped point u_rls/nr_x1[15]/q u_rls/nr_x1_reg[15]/QN -type DFF DFF
add mapped point u_rls/nr_x2[0]/q u_rls/nr_x2_reg[0]/Q -type DFF DFF
add mapped point u_rls/nr_x2[1]/q u_rls/nr_x2_reg[1]/Q -type DFF DFF
add mapped point u_rls/nr_x2[2]/q u_rls/nr_x2_reg[2]/Q -type DFF DFF
add mapped point u_rls/nr_x2[4]/q u_rls/nr_x2_reg[4]/Q -type DFF DFF
add mapped point u_rls/nr_x2[5]/q u_rls/nr_x2_reg[5]/Q -type DFF DFF
add mapped point u_rls/nr_x2[6]/q u_rls/nr_x2_reg[6]/Q -type DFF DFF
add mapped point u_rls/nr_x2[7]/q u_rls/nr_x2_reg[7]/Q -type DFF DFF
add mapped point u_rls/nr_x2[8]/q u_rls/nr_x2_reg[8]/Q -type DFF DFF
add mapped point u_rls/nr_x2[9]/q u_rls/nr_x2_reg[9]/Q -type DFF DFF
add mapped point u_rls/nr_x2[10]/q u_rls/nr_x2_reg[10]/Q -type DFF DFF
add mapped point u_rls/nr_x2[11]/q u_rls/nr_x2_reg[11]/Q -type DFF DFF
add mapped point u_rls/nr_x2[12]/q u_rls/nr_x2_reg[12]/Q -type DFF DFF
add mapped point u_rls/nr_x2[13]/q u_rls/nr_x2_reg[13]/Q -type DFF DFF
add mapped point u_rls/nr_x2[14]/q u_rls/nr_x2_reg[14]/Q -type DFF DFF
add mapped point u_rls/nr_x2[15]/q u_rls/nr_x2_reg[15]/Q -type DFF DFF
add mapped point u_rls/p_scalar[0]/q u_rls/p_scalar_reg[0]/Q -type DFF DFF
add mapped point u_rls/p_scalar[1]/q u_rls/p_scalar_reg[1]/QN -type DFF DFF
add mapped point u_rls/p_scalar[2]/q u_rls/p_scalar_reg[2]/QN -type DFF DFF
add mapped point u_rls/p_scalar[3]/q u_rls/p_scalar_reg[3]/QN -type DFF DFF
add mapped point u_rls/p_scalar[4]/q u_rls/p_scalar_reg[4]/QN -type DFF DFF
add mapped point u_rls/p_scalar[5]/q u_rls/p_scalar_reg[5]/QN -type DFF DFF
add mapped point u_rls/p_scalar[6]/q u_rls/p_scalar_reg[6]/QN -type DFF DFF
add mapped point u_rls/p_scalar[7]/q u_rls/p_scalar_reg[7]/QN -type DFF DFF
add mapped point u_rls/p_scalar[9]/q u_rls/p_scalar_reg[9]/QN -type DFF DFF
add mapped point u_rls/p_scalar[10]/q u_rls/p_scalar_reg[10]/QN -type DFF DFF
add mapped point u_rls/p_scalar[11]/q u_rls/p_scalar_reg[11]/Q -type DFF DFF
add mapped point u_rls/p_scalar[12]/q u_rls/p_scalar_reg[12]/QN -type DFF DFF
add mapped point u_rls/p_scalar[13]/q u_rls/p_scalar_reg[13]/QN -type DFF DFF
add mapped point u_rls/p_scalar[14]/q u_rls/p_scalar_reg[14]/QN -type DFF DFF
add mapped point u_rls/p_scalar[15]/q u_rls/p_scalar_reg[15]/Q -type DFF DFF
add mapped point u_rls/update_err[0]/q u_rls/update_err_reg[0]/Q -type DFF DFF
add mapped point u_rls/update_err[1]/q u_rls/update_err_reg[1]/Q -type DFF DFF
add mapped point u_rls/update_err[2]/q u_rls/update_err_reg[2]/Q -type DFF DFF
add mapped point u_rls/update_err[3]/q u_rls/update_err_reg[3]/Q -type DFF DFF
add mapped point u_rls/update_err[4]/q u_rls/update_err_reg[4]/Q -type DFF DFF
add mapped point u_rls/update_err[5]/q u_rls/update_err_reg[5]/Q -type DFF DFF
add mapped point u_rls/update_err[6]/q u_rls/update_err_reg[6]/Q -type DFF DFF
add mapped point u_rls/update_err[7]/q u_rls/update_err_reg[7]/Q -type DFF DFF
add mapped point u_rls/update_err[8]/q u_rls/update_err_reg[8]/Q -type DFF DFF
add mapped point u_rls/update_err[9]/q u_rls/update_err_reg[9]/Q -type DFF DFF
add mapped point u_rls/update_err[10]/q u_rls/update_err_reg[10]/Q -type DFF DFF
add mapped point u_rls/update_err[11]/q u_rls/update_err_reg[11]/Q -type DFF DFF
add mapped point u_rls/update_err[12]/q u_rls/update_err_reg[12]/Q -type DFF DFF
add mapped point u_rls/update_err[13]/q u_rls/update_err_reg[13]/Q -type DFF DFF
add mapped point u_rls/update_err[14]/q u_rls/update_err_reg[14]/Q -type DFF DFF
add mapped point u_rls/update_err[15]/q u_rls/update_err_reg[15]/Q -type DFF DFF
add mapped point u_rls/update_idx[0]/q u_rls/update_idx_reg[0]/Q -type DFF DFF
add mapped point u_rls/update_idx[1]/q u_rls/update_idx_reg[1]/Q -type DFF DFF
add mapped point u_rls/update_idx[2]/q u_rls/update_idx_reg[2]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[0]/q u_rls/update_p_over_denom_reg[0]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[1]/q u_rls/update_p_over_denom_reg[1]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[2]/q u_rls/update_p_over_denom_reg[2]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[3]/q u_rls/update_p_over_denom_reg[3]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[4]/q u_rls/update_p_over_denom_reg[4]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[5]/q u_rls/update_p_over_denom_reg[5]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[6]/q u_rls/update_p_over_denom_reg[6]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[7]/q u_rls/update_p_over_denom_reg[7]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[8]/q u_rls/update_p_over_denom_reg[8]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[9]/q u_rls/update_p_over_denom_reg[9]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[10]/q u_rls/update_p_over_denom_reg[10]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[11]/q u_rls/update_p_over_denom_reg[11]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[12]/q u_rls/update_p_over_denom_reg[12]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[13]/q u_rls/update_p_over_denom_reg[13]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[14]/q u_rls/update_p_over_denom_reg[14]/Q -type DFF DFF
add mapped point u_rls/update_p_over_denom[15]/q u_rls/update_p_over_denom_reg[15]/Q -type DFF DFF
add mapped point u_rls/valid_out/q u_rls/valid_out_reg/Q -type DFF DFF
add mapped point u_rls/w[0][0]/q u_rls/w_reg[0][0]/Q -type DFF DFF
add mapped point u_rls/w[0][1]/q u_rls/w_reg[0][1]/Q -type DFF DFF
add mapped point u_rls/w[0][2]/q u_rls/w_reg[0][2]/Q -type DFF DFF
add mapped point u_rls/w[0][3]/q u_rls/w_reg[0][3]/Q -type DFF DFF
add mapped point u_rls/w[0][4]/q u_rls/w_reg[0][4]/Q -type DFF DFF
add mapped point u_rls/w[0][5]/q u_rls/w_reg[0][5]/Q -type DFF DFF
add mapped point u_rls/w[0][6]/q u_rls/w_reg[0][6]/Q -type DFF DFF
add mapped point u_rls/w[0][7]/q u_rls/w_reg[0][7]/Q -type DFF DFF
add mapped point u_rls/w[0][8]/q u_rls/w_reg[0][8]/Q -type DFF DFF
add mapped point u_rls/w[0][9]/q u_rls/w_reg[0][9]/Q -type DFF DFF
add mapped point u_rls/w[0][10]/q u_rls/w_reg[0][10]/Q -type DFF DFF
add mapped point u_rls/w[0][11]/q u_rls/w_reg[0][11]/Q -type DFF DFF
add mapped point u_rls/w[0][12]/q u_rls/w_reg[0][12]/Q -type DFF DFF
add mapped point u_rls/w[0][13]/q u_rls/w_reg[0][13]/Q -type DFF DFF
add mapped point u_rls/w[0][14]/q u_rls/w_reg[0][14]/Q -type DFF DFF
add mapped point u_rls/w[0][15]/q u_rls/w_reg[0][15]/Q -type DFF DFF
add mapped point u_rls/w[1][0]/q u_rls/w_reg[1][0]/Q -type DFF DFF
add mapped point u_rls/w[1][1]/q u_rls/w_reg[1][1]/Q -type DFF DFF
add mapped point u_rls/w[1][2]/q u_rls/w_reg[1][2]/Q -type DFF DFF
add mapped point u_rls/w[1][3]/q u_rls/w_reg[1][3]/Q -type DFF DFF
add mapped point u_rls/w[1][4]/q u_rls/w_reg[1][4]/Q -type DFF DFF
add mapped point u_rls/w[1][5]/q u_rls/w_reg[1][5]/Q -type DFF DFF
add mapped point u_rls/w[1][6]/q u_rls/w_reg[1][6]/Q -type DFF DFF
add mapped point u_rls/w[1][7]/q u_rls/w_reg[1][7]/Q -type DFF DFF
add mapped point u_rls/w[1][8]/q u_rls/w_reg[1][8]/Q -type DFF DFF
add mapped point u_rls/w[1][9]/q u_rls/w_reg[1][9]/Q -type DFF DFF
add mapped point u_rls/w[1][10]/q u_rls/w_reg[1][10]/Q -type DFF DFF
add mapped point u_rls/w[1][11]/q u_rls/w_reg[1][11]/Q -type DFF DFF
add mapped point u_rls/w[1][12]/q u_rls/w_reg[1][12]/Q -type DFF DFF
add mapped point u_rls/w[1][13]/q u_rls/w_reg[1][13]/Q -type DFF DFF
add mapped point u_rls/w[1][14]/q u_rls/w_reg[1][14]/Q -type DFF DFF
add mapped point u_rls/w[1][15]/q u_rls/w_reg[1][15]/Q -type DFF DFF
add mapped point u_rls/w[2][0]/q u_rls/w_reg[2][0]/Q -type DFF DFF
add mapped point u_rls/w[2][1]/q u_rls/w_reg[2][1]/Q -type DFF DFF
add mapped point u_rls/w[2][2]/q u_rls/w_reg[2][2]/Q -type DFF DFF
add mapped point u_rls/w[2][3]/q u_rls/w_reg[2][3]/Q -type DFF DFF
add mapped point u_rls/w[2][4]/q u_rls/w_reg[2][4]/Q -type DFF DFF
add mapped point u_rls/w[2][5]/q u_rls/w_reg[2][5]/Q -type DFF DFF
add mapped point u_rls/w[2][6]/q u_rls/w_reg[2][6]/Q -type DFF DFF
add mapped point u_rls/w[2][7]/q u_rls/w_reg[2][7]/Q -type DFF DFF
add mapped point u_rls/w[2][8]/q u_rls/w_reg[2][8]/Q -type DFF DFF
add mapped point u_rls/w[2][9]/q u_rls/w_reg[2][9]/Q -type DFF DFF
add mapped point u_rls/w[2][10]/q u_rls/w_reg[2][10]/Q -type DFF DFF
add mapped point u_rls/w[2][11]/q u_rls/w_reg[2][11]/Q -type DFF DFF
add mapped point u_rls/w[2][12]/q u_rls/w_reg[2][12]/Q -type DFF DFF
add mapped point u_rls/w[2][13]/q u_rls/w_reg[2][13]/Q -type DFF DFF
add mapped point u_rls/w[2][14]/q u_rls/w_reg[2][14]/Q -type DFF DFF
add mapped point u_rls/w[2][15]/q u_rls/w_reg[2][15]/Q -type DFF DFF
add mapped point u_rls/w[3][0]/q u_rls/w_reg[3][0]/Q -type DFF DFF
add mapped point u_rls/w[3][1]/q u_rls/w_reg[3][1]/Q -type DFF DFF
add mapped point u_rls/w[3][2]/q u_rls/w_reg[3][2]/Q -type DFF DFF
add mapped point u_rls/w[3][3]/q u_rls/w_reg[3][3]/Q -type DFF DFF
add mapped point u_rls/w[3][4]/q u_rls/w_reg[3][4]/Q -type DFF DFF
add mapped point u_rls/w[3][5]/q u_rls/w_reg[3][5]/Q -type DFF DFF
add mapped point u_rls/w[3][6]/q u_rls/w_reg[3][6]/Q -type DFF DFF
add mapped point u_rls/w[3][7]/q u_rls/w_reg[3][7]/Q -type DFF DFF
add mapped point u_rls/w[3][8]/q u_rls/w_reg[3][8]/Q -type DFF DFF
add mapped point u_rls/w[3][9]/q u_rls/w_reg[3][9]/Q -type DFF DFF
add mapped point u_rls/w[3][10]/q u_rls/w_reg[3][10]/Q -type DFF DFF
add mapped point u_rls/w[3][11]/q u_rls/w_reg[3][11]/Q -type DFF DFF
add mapped point u_rls/w[3][12]/q u_rls/w_reg[3][12]/Q -type DFF DFF
add mapped point u_rls/w[3][13]/q u_rls/w_reg[3][13]/Q -type DFF DFF
add mapped point u_rls/w[3][14]/q u_rls/w_reg[3][14]/Q -type DFF DFF
add mapped point u_rls/w[3][15]/q u_rls/w_reg[3][15]/Q -type DFF DFF
add mapped point u_rls/w[4][0]/q u_rls/w_reg[4][0]/Q -type DFF DFF
add mapped point u_rls/w[4][1]/q u_rls/w_reg[4][1]/Q -type DFF DFF
add mapped point u_rls/w[4][2]/q u_rls/w_reg[4][2]/Q -type DFF DFF
add mapped point u_rls/w[4][3]/q u_rls/w_reg[4][3]/Q -type DFF DFF
add mapped point u_rls/w[4][4]/q u_rls/w_reg[4][4]/Q -type DFF DFF
add mapped point u_rls/w[4][5]/q u_rls/w_reg[4][5]/Q -type DFF DFF
add mapped point u_rls/w[4][6]/q u_rls/w_reg[4][6]/Q -type DFF DFF
add mapped point u_rls/w[4][7]/q u_rls/w_reg[4][7]/Q -type DFF DFF
add mapped point u_rls/w[4][8]/q u_rls/w_reg[4][8]/Q -type DFF DFF
add mapped point u_rls/w[4][9]/q u_rls/w_reg[4][9]/Q -type DFF DFF
add mapped point u_rls/w[4][10]/q u_rls/w_reg[4][10]/Q -type DFF DFF
add mapped point u_rls/w[4][11]/q u_rls/w_reg[4][11]/Q -type DFF DFF
add mapped point u_rls/w[4][12]/q u_rls/w_reg[4][12]/Q -type DFF DFF
add mapped point u_rls/w[4][13]/q u_rls/w_reg[4][13]/Q -type DFF DFF
add mapped point u_rls/w[4][14]/q u_rls/w_reg[4][14]/Q -type DFF DFF
add mapped point u_rls/w[4][15]/q u_rls/w_reg[4][15]/Q -type DFF DFF
add mapped point u_rls/w[5][0]/q u_rls/w_reg[5][0]/Q -type DFF DFF
add mapped point u_rls/w[5][1]/q u_rls/w_reg[5][1]/Q -type DFF DFF
add mapped point u_rls/w[5][2]/q u_rls/w_reg[5][2]/Q -type DFF DFF
add mapped point u_rls/w[5][3]/q u_rls/w_reg[5][3]/Q -type DFF DFF
add mapped point u_rls/w[5][4]/q u_rls/w_reg[5][4]/Q -type DFF DFF
add mapped point u_rls/w[5][5]/q u_rls/w_reg[5][5]/Q -type DFF DFF
add mapped point u_rls/w[5][6]/q u_rls/w_reg[5][6]/Q -type DFF DFF
add mapped point u_rls/w[5][7]/q u_rls/w_reg[5][7]/Q -type DFF DFF
add mapped point u_rls/w[5][8]/q u_rls/w_reg[5][8]/Q -type DFF DFF
add mapped point u_rls/w[5][9]/q u_rls/w_reg[5][9]/Q -type DFF DFF
add mapped point u_rls/w[5][10]/q u_rls/w_reg[5][10]/Q -type DFF DFF
add mapped point u_rls/w[5][11]/q u_rls/w_reg[5][11]/Q -type DFF DFF
add mapped point u_rls/w[5][12]/q u_rls/w_reg[5][12]/Q -type DFF DFF
add mapped point u_rls/w[5][13]/q u_rls/w_reg[5][13]/Q -type DFF DFF
add mapped point u_rls/w[5][14]/q u_rls/w_reg[5][14]/Q -type DFF DFF
add mapped point u_rls/w[5][15]/q u_rls/w_reg[5][15]/Q -type DFF DFF
add mapped point u_rls/w[6][0]/q u_rls/w_reg[6][0]/Q -type DFF DFF
add mapped point u_rls/w[6][1]/q u_rls/w_reg[6][1]/Q -type DFF DFF
add mapped point u_rls/w[6][2]/q u_rls/w_reg[6][2]/Q -type DFF DFF
add mapped point u_rls/w[6][3]/q u_rls/w_reg[6][3]/Q -type DFF DFF
add mapped point u_rls/w[6][4]/q u_rls/w_reg[6][4]/Q -type DFF DFF
add mapped point u_rls/w[6][5]/q u_rls/w_reg[6][5]/Q -type DFF DFF
add mapped point u_rls/w[6][6]/q u_rls/w_reg[6][6]/Q -type DFF DFF
add mapped point u_rls/w[6][7]/q u_rls/w_reg[6][7]/Q -type DFF DFF
add mapped point u_rls/w[6][8]/q u_rls/w_reg[6][8]/Q -type DFF DFF
add mapped point u_rls/w[6][9]/q u_rls/w_reg[6][9]/Q -type DFF DFF
add mapped point u_rls/w[6][10]/q u_rls/w_reg[6][10]/Q -type DFF DFF
add mapped point u_rls/w[6][11]/q u_rls/w_reg[6][11]/Q -type DFF DFF
add mapped point u_rls/w[6][12]/q u_rls/w_reg[6][12]/Q -type DFF DFF
add mapped point u_rls/w[6][13]/q u_rls/w_reg[6][13]/Q -type DFF DFF
add mapped point u_rls/w[6][14]/q u_rls/w_reg[6][14]/Q -type DFF DFF
add mapped point u_rls/w[6][15]/q u_rls/w_reg[6][15]/Q -type DFF DFF
add mapped point u_rls/w[7][0]/q u_rls/w_reg[7][0]/Q -type DFF DFF
add mapped point u_rls/w[7][1]/q u_rls/w_reg[7][1]/Q -type DFF DFF
add mapped point u_rls/w[7][2]/q u_rls/w_reg[7][2]/Q -type DFF DFF
add mapped point u_rls/w[7][3]/q u_rls/w_reg[7][3]/Q -type DFF DFF
add mapped point u_rls/w[7][4]/q u_rls/w_reg[7][4]/Q -type DFF DFF
add mapped point u_rls/w[7][5]/q u_rls/w_reg[7][5]/Q -type DFF DFF
add mapped point u_rls/w[7][6]/q u_rls/w_reg[7][6]/Q -type DFF DFF
add mapped point u_rls/w[7][7]/q u_rls/w_reg[7][7]/Q -type DFF DFF
add mapped point u_rls/w[7][8]/q u_rls/w_reg[7][8]/Q -type DFF DFF
add mapped point u_rls/w[7][9]/q u_rls/w_reg[7][9]/Q -type DFF DFF
add mapped point u_rls/w[7][10]/q u_rls/w_reg[7][10]/Q -type DFF DFF
add mapped point u_rls/w[7][11]/q u_rls/w_reg[7][11]/Q -type DFF DFF
add mapped point u_rls/w[7][12]/q u_rls/w_reg[7][12]/Q -type DFF DFF
add mapped point u_rls/w[7][13]/q u_rls/w_reg[7][13]/Q -type DFF DFF
add mapped point u_rls/w[7][14]/q u_rls/w_reg[7][14]/Q -type DFF DFF
add mapped point u_rls/w[7][15]/q u_rls/w_reg[7][15]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[15]/q u_rls/xTx_acc_reg[15]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[16]/q u_rls/xTx_acc_reg[16]/QN -type DFF DFF
add mapped point u_rls/xTx_acc[17]/q u_rls/xTx_acc_reg[17]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[18]/q u_rls/xTx_acc_reg[18]/QN -type DFF DFF
add mapped point u_rls/xTx_acc[19]/q u_rls/xTx_acc_reg[19]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[21]/q u_rls/xTx_acc_reg[21]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[23]/q u_rls/xTx_acc_reg[23]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[25]/q u_rls/xTx_acc_reg[25]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[26]/q u_rls/xTx_acc_reg[26]/QN -type DFF DFF
add mapped point u_rls/xTx_acc[27]/q u_rls/xTx_acc_reg[27]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[29]/q u_rls/xTx_acc_reg[29]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[30]/q u_rls/xTx_acc_reg[30]/QN -type DFF DFF
add mapped point u_rls/x_dly_p1[0][0]/q u_rls/x_dly_p1_reg[0][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][1]/q u_rls/x_dly_p1_reg[0][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][2]/q u_rls/x_dly_p1_reg[0][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][3]/q u_rls/x_dly_p1_reg[0][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][4]/q u_rls/x_dly_p1_reg[0][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][5]/q u_rls/x_dly_p1_reg[0][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][6]/q u_rls/x_dly_p1_reg[0][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][7]/q u_rls/x_dly_p1_reg[0][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][8]/q u_rls/x_dly_p1_reg[0][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][9]/q u_rls/x_dly_p1_reg[0][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][10]/q u_rls/x_dly_p1_reg[0][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][11]/q u_rls/x_dly_p1_reg[0][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][12]/q u_rls/x_dly_p1_reg[0][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][13]/q u_rls/x_dly_p1_reg[0][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][14]/q u_rls/x_dly_p1_reg[0][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[0][15]/q u_rls/x_dly_p1_reg[0][15]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][0]/q u_rls/x_dly_p1_reg[1][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][1]/q u_rls/x_dly_p1_reg[1][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][2]/q u_rls/x_dly_p1_reg[1][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][3]/q u_rls/x_dly_p1_reg[1][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][4]/q u_rls/x_dly_p1_reg[1][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][5]/q u_rls/x_dly_p1_reg[1][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][6]/q u_rls/x_dly_p1_reg[1][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][7]/q u_rls/x_dly_p1_reg[1][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][8]/q u_rls/x_dly_p1_reg[1][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][9]/q u_rls/x_dly_p1_reg[1][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][10]/q u_rls/x_dly_p1_reg[1][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][11]/q u_rls/x_dly_p1_reg[1][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][12]/q u_rls/x_dly_p1_reg[1][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][13]/q u_rls/x_dly_p1_reg[1][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][14]/q u_rls/x_dly_p1_reg[1][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[1][15]/q u_rls/x_dly_p1_reg[1][15]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][0]/q u_rls/x_dly_p1_reg[2][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][1]/q u_rls/x_dly_p1_reg[2][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][2]/q u_rls/x_dly_p1_reg[2][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][3]/q u_rls/x_dly_p1_reg[2][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][4]/q u_rls/x_dly_p1_reg[2][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][5]/q u_rls/x_dly_p1_reg[2][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][6]/q u_rls/x_dly_p1_reg[2][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][7]/q u_rls/x_dly_p1_reg[2][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][8]/q u_rls/x_dly_p1_reg[2][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][9]/q u_rls/x_dly_p1_reg[2][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][10]/q u_rls/x_dly_p1_reg[2][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][11]/q u_rls/x_dly_p1_reg[2][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][12]/q u_rls/x_dly_p1_reg[2][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][13]/q u_rls/x_dly_p1_reg[2][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][14]/q u_rls/x_dly_p1_reg[2][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[2][15]/q u_rls/x_dly_p1_reg[2][15]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][0]/q u_rls/x_dly_p1_reg[3][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][1]/q u_rls/x_dly_p1_reg[3][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][2]/q u_rls/x_dly_p1_reg[3][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][3]/q u_rls/x_dly_p1_reg[3][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][4]/q u_rls/x_dly_p1_reg[3][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][5]/q u_rls/x_dly_p1_reg[3][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][6]/q u_rls/x_dly_p1_reg[3][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][7]/q u_rls/x_dly_p1_reg[3][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][8]/q u_rls/x_dly_p1_reg[3][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][9]/q u_rls/x_dly_p1_reg[3][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][10]/q u_rls/x_dly_p1_reg[3][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][11]/q u_rls/x_dly_p1_reg[3][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][12]/q u_rls/x_dly_p1_reg[3][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][13]/q u_rls/x_dly_p1_reg[3][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][14]/q u_rls/x_dly_p1_reg[3][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[3][15]/q u_rls/x_dly_p1_reg[3][15]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][0]/q u_rls/x_dly_p1_reg[4][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][1]/q u_rls/x_dly_p1_reg[4][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][2]/q u_rls/x_dly_p1_reg[4][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][3]/q u_rls/x_dly_p1_reg[4][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][4]/q u_rls/x_dly_p1_reg[4][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][5]/q u_rls/x_dly_p1_reg[4][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][6]/q u_rls/x_dly_p1_reg[4][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][7]/q u_rls/x_dly_p1_reg[4][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][8]/q u_rls/x_dly_p1_reg[4][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][9]/q u_rls/x_dly_p1_reg[4][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][10]/q u_rls/x_dly_p1_reg[4][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][11]/q u_rls/x_dly_p1_reg[4][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][12]/q u_rls/x_dly_p1_reg[4][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][13]/q u_rls/x_dly_p1_reg[4][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][14]/q u_rls/x_dly_p1_reg[4][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[4][15]/q u_rls/x_dly_p1_reg[4][15]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][0]/q u_rls/x_dly_p1_reg[5][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][1]/q u_rls/x_dly_p1_reg[5][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][2]/q u_rls/x_dly_p1_reg[5][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][3]/q u_rls/x_dly_p1_reg[5][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][4]/q u_rls/x_dly_p1_reg[5][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][5]/q u_rls/x_dly_p1_reg[5][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][6]/q u_rls/x_dly_p1_reg[5][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][7]/q u_rls/x_dly_p1_reg[5][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][8]/q u_rls/x_dly_p1_reg[5][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][9]/q u_rls/x_dly_p1_reg[5][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][10]/q u_rls/x_dly_p1_reg[5][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][11]/q u_rls/x_dly_p1_reg[5][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][12]/q u_rls/x_dly_p1_reg[5][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][13]/q u_rls/x_dly_p1_reg[5][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][14]/q u_rls/x_dly_p1_reg[5][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[5][15]/q u_rls/x_dly_p1_reg[5][15]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][0]/q u_rls/x_dly_p1_reg[6][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][1]/q u_rls/x_dly_p1_reg[6][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][2]/q u_rls/x_dly_p1_reg[6][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][3]/q u_rls/x_dly_p1_reg[6][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][4]/q u_rls/x_dly_p1_reg[6][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][5]/q u_rls/x_dly_p1_reg[6][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][6]/q u_rls/x_dly_p1_reg[6][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][7]/q u_rls/x_dly_p1_reg[6][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][8]/q u_rls/x_dly_p1_reg[6][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][9]/q u_rls/x_dly_p1_reg[6][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][10]/q u_rls/x_dly_p1_reg[6][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][11]/q u_rls/x_dly_p1_reg[6][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][12]/q u_rls/x_dly_p1_reg[6][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][13]/q u_rls/x_dly_p1_reg[6][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][14]/q u_rls/x_dly_p1_reg[6][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[6][15]/q u_rls/x_dly_p1_reg[6][15]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][0]/q u_rls/x_dly_p1_reg[7][0]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][1]/q u_rls/x_dly_p1_reg[7][1]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][2]/q u_rls/x_dly_p1_reg[7][2]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][3]/q u_rls/x_dly_p1_reg[7][3]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][4]/q u_rls/x_dly_p1_reg[7][4]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][5]/q u_rls/x_dly_p1_reg[7][5]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][6]/q u_rls/x_dly_p1_reg[7][6]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][7]/q u_rls/x_dly_p1_reg[7][7]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][8]/q u_rls/x_dly_p1_reg[7][8]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][9]/q u_rls/x_dly_p1_reg[7][9]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][10]/q u_rls/x_dly_p1_reg[7][10]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][11]/q u_rls/x_dly_p1_reg[7][11]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][12]/q u_rls/x_dly_p1_reg[7][12]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][13]/q u_rls/x_dly_p1_reg[7][13]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][14]/q u_rls/x_dly_p1_reg[7][14]/Q -type DFF DFF
add mapped point u_rls/x_dly_p1[7][15]/q u_rls/x_dly_p1_reg[7][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][0]/q u_rls/x_dly_reg[0][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][1]/q u_rls/x_dly_reg[0][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][2]/q u_rls/x_dly_reg[0][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][3]/q u_rls/x_dly_reg[0][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][4]/q u_rls/x_dly_reg[0][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][5]/q u_rls/x_dly_reg[0][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][6]/q u_rls/x_dly_reg[0][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][7]/q u_rls/x_dly_reg[0][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][8]/q u_rls/x_dly_reg[0][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][9]/q u_rls/x_dly_reg[0][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][10]/q u_rls/x_dly_reg[0][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][11]/q u_rls/x_dly_reg[0][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][12]/q u_rls/x_dly_reg[0][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][13]/q u_rls/x_dly_reg[0][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][14]/q u_rls/x_dly_reg[0][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[0][15]/q u_rls/x_dly_reg[0][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][0]/q u_rls/x_dly_reg[1][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][1]/q u_rls/x_dly_reg[1][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][2]/q u_rls/x_dly_reg[1][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][3]/q u_rls/x_dly_reg[1][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][4]/q u_rls/x_dly_reg[1][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][5]/q u_rls/x_dly_reg[1][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][6]/q u_rls/x_dly_reg[1][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][7]/q u_rls/x_dly_reg[1][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][8]/q u_rls/x_dly_reg[1][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][9]/q u_rls/x_dly_reg[1][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][10]/q u_rls/x_dly_reg[1][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][11]/q u_rls/x_dly_reg[1][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][12]/q u_rls/x_dly_reg[1][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][13]/q u_rls/x_dly_reg[1][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][14]/q u_rls/x_dly_reg[1][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[1][15]/q u_rls/x_dly_reg[1][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][0]/q u_rls/x_dly_reg[2][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][1]/q u_rls/x_dly_reg[2][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][2]/q u_rls/x_dly_reg[2][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][3]/q u_rls/x_dly_reg[2][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][4]/q u_rls/x_dly_reg[2][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][5]/q u_rls/x_dly_reg[2][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][6]/q u_rls/x_dly_reg[2][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][7]/q u_rls/x_dly_reg[2][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][8]/q u_rls/x_dly_reg[2][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][9]/q u_rls/x_dly_reg[2][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][10]/q u_rls/x_dly_reg[2][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][11]/q u_rls/x_dly_reg[2][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][12]/q u_rls/x_dly_reg[2][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][13]/q u_rls/x_dly_reg[2][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][14]/q u_rls/x_dly_reg[2][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[2][15]/q u_rls/x_dly_reg[2][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][0]/q u_rls/x_dly_reg[3][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][1]/q u_rls/x_dly_reg[3][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][2]/q u_rls/x_dly_reg[3][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][3]/q u_rls/x_dly_reg[3][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][4]/q u_rls/x_dly_reg[3][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][5]/q u_rls/x_dly_reg[3][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][6]/q u_rls/x_dly_reg[3][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][7]/q u_rls/x_dly_reg[3][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][8]/q u_rls/x_dly_reg[3][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][9]/q u_rls/x_dly_reg[3][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][10]/q u_rls/x_dly_reg[3][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][11]/q u_rls/x_dly_reg[3][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][12]/q u_rls/x_dly_reg[3][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][13]/q u_rls/x_dly_reg[3][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][14]/q u_rls/x_dly_reg[3][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[3][15]/q u_rls/x_dly_reg[3][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][0]/q u_rls/x_dly_reg[4][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][1]/q u_rls/x_dly_reg[4][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][2]/q u_rls/x_dly_reg[4][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][3]/q u_rls/x_dly_reg[4][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][4]/q u_rls/x_dly_reg[4][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][5]/q u_rls/x_dly_reg[4][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][6]/q u_rls/x_dly_reg[4][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][7]/q u_rls/x_dly_reg[4][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][8]/q u_rls/x_dly_reg[4][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][9]/q u_rls/x_dly_reg[4][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][10]/q u_rls/x_dly_reg[4][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][11]/q u_rls/x_dly_reg[4][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][12]/q u_rls/x_dly_reg[4][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][13]/q u_rls/x_dly_reg[4][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][14]/q u_rls/x_dly_reg[4][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[4][15]/q u_rls/x_dly_reg[4][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][0]/q u_rls/x_dly_reg[5][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][1]/q u_rls/x_dly_reg[5][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][2]/q u_rls/x_dly_reg[5][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][3]/q u_rls/x_dly_reg[5][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][4]/q u_rls/x_dly_reg[5][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][5]/q u_rls/x_dly_reg[5][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][6]/q u_rls/x_dly_reg[5][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][7]/q u_rls/x_dly_reg[5][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][8]/q u_rls/x_dly_reg[5][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][9]/q u_rls/x_dly_reg[5][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][10]/q u_rls/x_dly_reg[5][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][11]/q u_rls/x_dly_reg[5][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][12]/q u_rls/x_dly_reg[5][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][13]/q u_rls/x_dly_reg[5][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][14]/q u_rls/x_dly_reg[5][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[5][15]/q u_rls/x_dly_reg[5][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][0]/q u_rls/x_dly_reg[6][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][1]/q u_rls/x_dly_reg[6][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][2]/q u_rls/x_dly_reg[6][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][3]/q u_rls/x_dly_reg[6][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][4]/q u_rls/x_dly_reg[6][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][5]/q u_rls/x_dly_reg[6][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][6]/q u_rls/x_dly_reg[6][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][7]/q u_rls/x_dly_reg[6][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][8]/q u_rls/x_dly_reg[6][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][9]/q u_rls/x_dly_reg[6][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][10]/q u_rls/x_dly_reg[6][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][11]/q u_rls/x_dly_reg[6][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][12]/q u_rls/x_dly_reg[6][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][13]/q u_rls/x_dly_reg[6][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][14]/q u_rls/x_dly_reg[6][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[6][15]/q u_rls/x_dly_reg[6][15]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][0]/q u_rls/x_dly_reg[7][0]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][1]/q u_rls/x_dly_reg[7][1]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][2]/q u_rls/x_dly_reg[7][2]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][3]/q u_rls/x_dly_reg[7][3]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][4]/q u_rls/x_dly_reg[7][4]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][5]/q u_rls/x_dly_reg[7][5]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][6]/q u_rls/x_dly_reg[7][6]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][7]/q u_rls/x_dly_reg[7][7]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][8]/q u_rls/x_dly_reg[7][8]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][9]/q u_rls/x_dly_reg[7][9]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][10]/q u_rls/x_dly_reg[7][10]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][11]/q u_rls/x_dly_reg[7][11]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][12]/q u_rls/x_dly_reg[7][12]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][13]/q u_rls/x_dly_reg[7][13]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][14]/q u_rls/x_dly_reg[7][14]/Q -type DFF DFF
add mapped point u_rls/x_dly[7][15]/q u_rls/x_dly_reg[7][15]/Q -type DFF DFF
add mapped point u_rls/y_acc[0]/q u_rls/y_acc_reg[0]/Q -type DFF DFF
add mapped point u_rls/y_acc[1]/q u_rls/y_acc_reg[1]/Q -type DFF DFF
add mapped point u_rls/y_acc[2]/q u_rls/y_acc_reg[2]/Q -type DFF DFF
add mapped point u_rls/y_acc[3]/q u_rls/y_acc_reg[3]/Q -type DFF DFF
add mapped point u_rls/y_acc[4]/q u_rls/y_acc_reg[4]/Q -type DFF DFF
add mapped point u_rls/y_acc[5]/q u_rls/y_acc_reg[5]/Q -type DFF DFF
add mapped point u_rls/y_acc[6]/q u_rls/y_acc_reg[6]/Q -type DFF DFF
add mapped point u_rls/y_acc[7]/q u_rls/y_acc_reg[7]/Q -type DFF DFF
add mapped point u_rls/y_acc[8]/q u_rls/y_acc_reg[8]/Q -type DFF DFF
add mapped point u_rls/y_acc[9]/q u_rls/y_acc_reg[9]/Q -type DFF DFF
add mapped point u_rls/y_acc[10]/q u_rls/y_acc_reg[10]/Q -type DFF DFF
add mapped point u_rls/y_acc[11]/q u_rls/y_acc_reg[11]/Q -type DFF DFF
add mapped point u_rls/y_acc[12]/q u_rls/y_acc_reg[12]/Q -type DFF DFF
add mapped point u_rls/y_acc[13]/q u_rls/y_acc_reg[13]/Q -type DFF DFF
add mapped point u_rls/y_acc[14]/q u_rls/y_acc_reg[14]/Q -type DFF DFF
add mapped point u_rls/y_acc[15]/q u_rls/y_acc_reg[15]/Q -type DFF DFF
add mapped point u_rls/y_acc[16]/q u_rls/y_acc_reg[16]/Q -type DFF DFF
add mapped point u_rls/y_acc[17]/q u_rls/y_acc_reg[17]/Q -type DFF DFF
add mapped point u_rls/y_acc[18]/q u_rls/y_acc_reg[18]/Q -type DFF DFF
add mapped point u_rls/y_acc[19]/q u_rls/y_acc_reg[19]/Q -type DFF DFF
add mapped point u_rls/y_acc[20]/q u_rls/y_acc_reg[20]/Q -type DFF DFF
add mapped point u_rls/y_acc[21]/q u_rls/y_acc_reg[21]/Q -type DFF DFF
add mapped point u_rls/y_acc[22]/q u_rls/y_acc_reg[22]/Q -type DFF DFF
add mapped point u_rls/y_acc[23]/q u_rls/y_acc_reg[23]/Q -type DFF DFF
add mapped point u_rls/y_acc[24]/q u_rls/y_acc_reg[24]/Q -type DFF DFF
add mapped point u_rls/y_acc[25]/q u_rls/y_acc_reg[25]/Q -type DFF DFF
add mapped point u_rls/y_acc[26]/q u_rls/y_acc_reg[26]/Q -type DFF DFF
add mapped point u_rls/y_acc[27]/q u_rls/y_acc_reg[27]/Q -type DFF DFF
add mapped point u_rls/y_acc[28]/q u_rls/y_acc_reg[28]/Q -type DFF DFF
add mapped point u_rls/y_acc[29]/q u_rls/y_acc_reg[29]/Q -type DFF DFF
add mapped point u_rls/y_acc[30]/q u_rls/y_acc_reg[30]/Q -type DFF DFF
add mapped point u_rls/y_acc[31]/q u_rls/y_acc_reg[31]/Q -type DFF DFF
add mapped point u_rls/y_acc[32]/q u_rls/y_acc_reg[32]/Q -type DFF DFF
add mapped point u_rls/y_acc[33]/q u_rls/y_acc_reg[33]/Q -type DFF DFF
add mapped point u_rls/y_acc[34]/q u_rls/y_acc_reg[34]/Q -type DFF DFF
add mapped point u_rls/y_hat[0]/q u_rls/y_hat_reg[0]/Q -type DFF DFF
add mapped point u_rls/y_hat[1]/q u_rls/y_hat_reg[1]/Q -type DFF DFF
add mapped point u_rls/y_hat[2]/q u_rls/y_hat_reg[2]/Q -type DFF DFF
add mapped point u_rls/y_hat[3]/q u_rls/y_hat_reg[3]/Q -type DFF DFF
add mapped point u_rls/y_hat[4]/q u_rls/y_hat_reg[4]/Q -type DFF DFF
add mapped point u_rls/y_hat[5]/q u_rls/y_hat_reg[5]/Q -type DFF DFF
add mapped point u_rls/y_hat[6]/q u_rls/y_hat_reg[6]/Q -type DFF DFF
add mapped point u_rls/y_hat[7]/q u_rls/y_hat_reg[7]/Q -type DFF DFF
add mapped point u_rls/y_hat[8]/q u_rls/y_hat_reg[8]/Q -type DFF DFF
add mapped point u_rls/y_hat[9]/q u_rls/y_hat_reg[9]/Q -type DFF DFF
add mapped point u_rls/y_hat[10]/q u_rls/y_hat_reg[10]/Q -type DFF DFF
add mapped point u_rls/y_hat[11]/q u_rls/y_hat_reg[11]/Q -type DFF DFF
add mapped point u_rls/y_hat[12]/q u_rls/y_hat_reg[12]/Q -type DFF DFF
add mapped point u_rls/y_hat[13]/q u_rls/y_hat_reg[13]/Q -type DFF DFF
add mapped point u_rls/y_hat[14]/q u_rls/y_hat_reg[14]/Q -type DFF DFF
add mapped point u_rls/y_hat[15]/q u_rls/y_hat_reg[15]/Q -type DFF DFF
add mapped point u_rls/nr_p2_valid/q u_rls/nr_p2_valid_reg/Q -type DFF DFF
add mapped point u_rls/nr_x2[3]/q u_rls/nr_x2_reg[3]/Q -type DFF DFF
add mapped point u_rls/p_scalar[8]/q u_rls/p_scalar_reg[8]/Q -type DFF DFF
add mapped point u_rls/s1_valid/q u_rls/s1_valid_reg/Q -type DFF DFF
add mapped point u_rls/update_busy/q u_rls/update_busy_reg/Q -type DFF DFF
add mapped point u_rls/xTx_acc[20]/q u_rls/xTx_acc_reg[20]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[22]/q u_rls/xTx_acc_reg[22]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[24]/q u_rls/xTx_acc_reg[24]/Q -type DFF DFF
add mapped point u_rls/xTx_acc[28]/q u_rls/xTx_acc_reg[28]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
